version: '3'

services:
  server:
    build: ./server
    ports:
      - '8080:8080'
  database:
    container_name: database
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db:rw

volumes:
  mongo_data:
