version: '3'

services:
  server:
    image: mihaipredoiu/pluto-idp-server:latest
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - '8080:8080'
    networks:
      - 'plutonet'
  client:
    image: mihaipredoiu/pluto-idp-client:latest
    deploy:
      replicas: 4
      restart_policy:
        condition: on-failure
    ports:
      - '8081:8081'
    command: tail -f /dev/null
    networks:
      - 'plutonet'
  notifier:
    image: mihaipredoiu/pluto-idp-notifier:latest
    ports:
      - '8082:8082'
    networks:
      - 'plutonet'
  database:
    image: mongo:latest
    deploy:
      placement:
        constraints: [node.role == manager]
    ports:
      - '27017:27017'
    networks:
      - 'plutonet'
    volumes:
      - mongo_data:/data/db:rw

  prometheus:
    image: mihaipredoiu/pluto-idp-metrics:latest
    ports:
      - '9090:9090'
    networks:
      - 'plutonet'

  node-exporter:
    image: prom/node-exporter:latest
    ports:
      - '9100:9100'
    networks:
      - 'plutonet'

volumes:
  mongo_data:

networks:
  plutonet:
