version: '3'

services:
  server:
    container_name: server
    build: ./server
    ports:
      - '8080:8080'
    links:
      - database
  client:
    container_name: client
    build: ./client
    ports:
      - '8081:8081'
    command: tail -f /dev/null
  notifier:
    container_name: notifier
    build: ./email_notifier
    ports:
      - '8082:8082'
  database:
    container_name: database
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db:rw

  # prometheus:
  #   image: prom/prometheus:0.18.0
  #   volumes:
  #     - ./metrics/prometheus.yml:/etc/prometheus/prometheus.yml
  #   command:
  #     - '-config.file=/etc/prometheus/prometheus.yml'
  #   ports:
  #     - '9090:9090'
  # node-exporter:
  #   image: prom/node-exporter:v0.18.1
  #   ports:
  #     - '9100:9100'
#  grafana:
#        image: grafana/grafana:3.0.0-beta7
#        environment:
#            - GF_SECURITY_ADMIN_PASSWORD=pass
#        depends_on:
#            - prometheus
#        ports:
#            - "3000:3000"

volumes:
  mongo_data:
