global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets:
          - 'localhost:9090'
  - job_name: 'pluto_backend'
    static_configs:
      - targets:
          - 'server:8080'
  - job_name: 'node_exporter'
    static_configs:
      - targets:
          - 'node-exporter:9100'
